#!/bin/bash

ws=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)
path="$HOME/.config/scripts/wsanimation"

for i in {1..6} 
do
    if [[ "$ws" == "$i" ]] ; then
        eww -c $path update class$i="active"

    else 
        eww -c $path update class$i="inactive"

    fi

done


eww -c ~/.config/scripts/wsanimation open wsanim
sleep 3s
eww -c ~/.config/scripts/wsanimation close wsanim



